// THIS FILE HAS BEEN GENERATED BY A PREPROCESSOR.
package net.sourceforge.plantuml.svek;

import net.sourceforge.plantuml.abel.Hideable;
import net.sourceforge.plantuml.klimt.font.StringBounder;
import net.sourceforge.plantuml.klimt.geom.MagneticBorder;
import net.sourceforge.plantuml.klimt.shape.TextBlock;

public interface IEntityImage extends Hideable, TextBlock {

	public static final int CORNER = 25;
	public static final int MARGIN = 5;
	public static final int MARGIN_LINE = 5;

	public ShapeType getShapeType();

	public Margins getShield(StringBounder stringBounder);

	public double getOverscanX(StringBounder stringBounder);

	public MagneticBorder getMagneticBorder();

}
