// THIS FILE HAS BEEN GENERATED BY A PREPROCESSOR.
package net.sourceforge.plantuml.svek;

import net.sourceforge.plantuml.klimt.font.StringBounder;

public interface WithPorts {

	Ports getPorts(StringBounder stringBounder);

}
