// THIS FILE HAS BEEN GENERATED BY A PREPROCESSOR.
package net.sourceforge.plantuml.project.lang;

import net.sourceforge.plantuml.regex.IRegex;

public interface Verb {

	public IRegex toRegex();

}
