// THIS FILE HAS BEEN GENERATED BY A PREPROCESSOR.

package smetana.core;

public interface __ptr__  {

	public boolean isSameThan(__ptr__ other);

	public __ptr__ castTo(Class dest);
	
	public Object getTheField(FieldOffset bytes);
	
	public __ptr__ unsupported();
	

}
