// THIS FILE HAS BEEN GENERATED BY A PREPROCESSOR.
package smetana.core;

import com.plantuml.api.cheerpj.WasmLog;

final public class Memory {

	public static void free(Object arg) {
	}

	public static int identityHashCode(Globals zz, CString data) {
		if (data == null)
			return 0;

		int result = data.getUid();
		zz.all.put(result, data);
		WasmLog.log("hashsize = " + zz.all.size());
		return result;
	}

	public static CString fromIdentityHashCode(Globals zz, int hash) {
		if (hash % 2 != 0)
			throw new IllegalArgumentException();

		Object result = zz.all.get(hash);
		if (result == null)
			throw new UnsupportedOperationException();

		return (CString) result;
	}

}
