// THIS FILE HAS BEEN GENERATED BY A PREPROCESSOR.
package net.sourceforge.plantuml.klimt.drawing.svg;

public enum LengthAdjust {
	NONE, SPACING, SPACING_AND_GLYPHS;

	public static LengthAdjust defaultValue() {
		return SPACING;
	}
}
