// THIS FILE HAS BEEN GENERATED BY A PREPROCESSOR.
package net.sourceforge.plantuml.klimt.color;

public class NoSuchColorException extends Exception {

	public NoSuchColorException() {
		super("NoSuchColorException");
	}

}
