// THIS FILE HAS BEEN GENERATED BY A PREPROCESSOR.

package smetana.core.debug;

public final class SmetanaDebug {
    // ::remove folder when __HAXE__

	static public void LOG(String s) {

	}

	static public void ENTERING(String signature, String methodName) {
	}

	static public void LEAVING(String signature, String methodName) {
	}

	public static void reset() {
	}

	public static void printMe() {
	}

}
