// THIS FILE HAS BEEN GENERATED BY A PREPROCESSOR.
package net.sourceforge.plantuml.code;

public class CompressionNone implements Compression {
    // ::remove folder when __HAXE__

	public byte[] compress(byte[] in) {
		return in;
	}

	public ByteArray decompress(byte[] in) {
		return ByteArray.from(in);
	}

}
