// THIS FILE HAS BEEN GENERATED BY A PREPROCESSOR.
package net.sourceforge.plantuml.code;

public class TranscoderUtil {
	public static Transcoder getDefaultTranscoder() {
		return new TranscoderSmart();
	}


}
