// THIS FILE HAS BEEN GENERATED BY A PREPROCESSOR.
package net.sourceforge.plantuml.decoration.symbol;

import net.sourceforge.plantuml.klimt.Fashion;
import net.sourceforge.plantuml.klimt.shape.TextBlock;
import net.sourceforge.plantuml.style.SName;
import net.sourceforge.plantuml.svek.Control;

class USymbolControl extends USymbolSimpleAbstract {

	@Override
	public SName getSName() {
		return SName.control;
	}

	@Override
	protected TextBlock getDrawing(final Fashion symbolContext) {
		return new Control(symbolContext.withDeltaShadow(symbolContext.isShadowing() ? 4.0 : 0.0));
	}

}
