// THIS FILE HAS BEEN GENERATED BY A PREPROCESSOR.
package net.sourceforge.plantuml.decoration.symbol;

import net.sourceforge.plantuml.klimt.Fashion;
import net.sourceforge.plantuml.klimt.shape.TextBlock;
import net.sourceforge.plantuml.skin.ActorStyle;
import net.sourceforge.plantuml.style.SName;

public class USymbolActorBusiness extends USymbolSimpleAbstract {

	private final ActorStyle actorStyle = ActorStyle.STICKMAN_BUSINESS;

	@Override
	public SName getSName() {
		return SName.business;
	}

	@Override
	protected TextBlock getDrawing(Fashion symbolContext) {
		return actorStyle.getTextBlock(symbolContext);
	}

}
