// THIS FILE HAS BEEN GENERATED BY A PREPROCESSOR.
package net.sourceforge.plantuml.abel;

import java.util.Collection;

import net.sourceforge.plantuml.stereo.Stereotype;

public interface IEntityFactory {

	public boolean isRemoved(Stereotype stereotype);

	public Collection<Entity> leafs();

}
