// THIS FILE HAS BEEN GENERATED BY A PREPROCESSOR.
package net.sourceforge.plantuml.abel;

import net.sourceforge.plantuml.klimt.color.ColorType;
import net.sourceforge.plantuml.klimt.color.Colors;
import net.sourceforge.plantuml.klimt.color.HColor;

public interface LineConfigurable {

	public Colors getColors();

	public void setSpecificColorTOBEREMOVED(ColorType type, HColor color);

}
