// THIS FILE HAS BEEN GENERATED BY A PREPROCESSOR.
package net.sourceforge.plantuml;

import net.sourceforge.plantuml.abel.DisplayPositioned;
import net.sourceforge.plantuml.abel.DisplayPositionned;
import net.sourceforge.plantuml.cucadiagram.DisplaySection;
import net.sourceforge.plantuml.klimt.creole.Display;

public interface Annotated {

	public DisplayPositionned getTitle();

	public DisplayPositioned getCaption();

	public DisplayPositioned getLegend();

	public DisplaySection getHeader();

	public DisplaySection getFooter();

	public Display getMainFrame();

}
