// THIS FILE HAS BEEN GENERATED BY A PREPROCESSOR.
package net.sourceforge.plantuml.nwdiag.core;

import net.sourceforge.plantuml.klimt.color.HColor;

public interface NStackable {

	public void setDescription(String description);

	public void setColor(HColor color);

}
