// THIS FILE HAS BEEN GENERATED BY A PREPROCESSOR.
package net.sourceforge.plantuml.klimt.geom;

public interface Positionable extends Moveable {

	public XDimension2D getSize();

	public XPoint2D getPosition();

}
