// THIS FILE HAS BEEN GENERATED BY A PREPROCESSOR.
package net.sourceforge.plantuml.klimt.shape;

import net.sourceforge.plantuml.klimt.drawing.UGraphic;
import net.sourceforge.plantuml.klimt.font.StringBounder;
import net.sourceforge.plantuml.klimt.geom.XDimension2D;

public class TileImageSvg extends AbstractTextBlock implements TextBlock {

	private final UImageSvg svg;
	private final double scale;

	public TileImageSvg(String svg, double scale) {
		this.svg = new UImageSvg(svg, scale);
		this.scale = scale;
	}

	public XDimension2D calculateDimension(StringBounder stringBounder) {
		return new XDimension2D(svg.getWidth(), svg.getHeight());
	}

	public void drawU(UGraphic ug) {
		ug.draw(svg);
	}

}
