// THIS FILE HAS BEEN GENERATED BY A PREPROCESSOR.
package net.sourceforge.plantuml.klimt.shape;

import net.sourceforge.plantuml.klimt.UChange;

public enum UHidden implements UChange {

	NORMAL_SHOWN, HIDDEN;

}
