// THIS FILE HAS BEEN GENERATED BY A PREPROCESSOR.
package h;

import smetana.core.CString;
import smetana.core.UnsupportedStarStruct;

final public class ST_fontinfo extends UnsupportedStarStruct {


	public double fontsize;
	public CString fontname;
	public CString fontcolor;


}

// struct fontinfo {
// double fontsize;
// char *fontname;
// char *fontcolor;
// };
