// THIS FILE HAS BEEN GENERATED BY A PREPROCESSOR.
package h;

import smetana.core.UnsupportedStarStruct;

final public class ST_LeafList_t extends UnsupportedStarStruct {

	public ST_LeafList_t next;
	// WARNING
	public ST_Branch_t /* ST_Leaf_t */leaf;



	// typedef struct LeafList {
	// struct LeafList *next;
	// Leaf_t *leaf;
	// } LeafList_t;

}
