// THIS FILE HAS BEEN GENERATED BY A PREPROCESSOR.
package h;

import smetana.core.UnsupportedStarStruct;

final public class ST_tna_t extends UnsupportedStarStruct {

	public double t;
	public final ST_pointf a[] = new ST_pointf[] { new ST_pointf(), new ST_pointf() };
	

}

// typedef struct tna_t {
// double t;
// Ppoint_t a[2];
// } tna_t;
