// THIS FILE HAS BEEN GENERATED BY A PREPROCESSOR.
package net.sourceforge.plantuml.file;

import java.io.IOException;

public interface AParentFolder {

	public AFile getAFile(String nameOrPath) throws IOException;

}
