// THIS FILE HAS BEEN GENERATED BY A PREPROCESSOR.
package net.sourceforge.plantuml.klimt.font;

import net.sourceforge.plantuml.klimt.geom.XDimension2D;

public interface StringBounder {

	// ::comment when __HAXE__
	public XDimension2D calculateDimension(UFont font, String text);

	public double getDescent(UFont font, String text);

	public boolean matchesProperty(String propertyName);

}
