// THIS FILE HAS BEEN GENERATED BY A PREPROCESSOR.
package net.sourceforge.plantuml.api;

public interface INumberAnalyzed {

	public long getNb();

	public long getSum();

	public long getMin();

	public long getMax();

	public long getMean();

	public long getSliddingMean();

}
