// THIS FILE HAS BEEN GENERATED BY A PREPROCESSOR.
package net.sourceforge.plantuml.project.core;

import net.sourceforge.plantuml.project.time.Day;

public interface Moment {

	public Day getStart();

	public Day getEnd();

}
