// THIS FILE HAS BEEN GENERATED BY A PREPROCESSOR.
package net.sourceforge.plantuml.klimt.creole;

import net.sourceforge.plantuml.klimt.font.StringBounder;

public interface Stencil {

	public double getStartingX(StringBounder stringBounder, double y);

	public double getEndingX(StringBounder stringBounder, double y);

}
