// THIS FILE HAS BEEN GENERATED BY A PREPROCESSOR.
package net.sourceforge.plantuml.style;

public interface WithStyle extends Styleable {
    // ::remove file when __HAXE__

	public Style[] getUsedStyles();

}
