// THIS FILE HAS BEEN GENERATED BY A PREPROCESSOR.
package net.sourceforge.plantuml.klimt.drawing;

import java.io.IOException;
import java.io.OutputStream;

import net.sourceforge.plantuml.FileFormat;
import net.sourceforge.plantuml.klimt.color.ColorMapper;
import net.sourceforge.plantuml.klimt.color.HColors;
import net.sourceforge.plantuml.klimt.geom.EnsureVisible;

public class UGraphicNull extends AbstractUGraphic<String> implements EnsureVisible {

	@Override
	protected AbstractCommonUGraphic copyUGraphic() {
		final UGraphicNull result = new UGraphicNull(this);
		return result;
	}

	private UGraphicNull(UGraphicNull other) {
		super(FileFormat.PNG.getDefaultStringBounder());
		copy(other);
	}

	public UGraphicNull() {
		super(FileFormat.PNG.getDefaultStringBounder());
		copy(HColors.BLACK, ColorMapper.IDENTITY, "foo");
	}

	@Override
	public void writeToStream(OutputStream os, String metadata, int dpi) throws IOException {
	}

	public void ensureVisible(double x, double y) {
	}

}
