// THIS FILE HAS BEEN GENERATED BY A PREPROCESSOR.
package net.sourceforge.plantuml.klimt;

public interface Shadowable extends UShape {

	public void setDeltaShadow(double deltaShadow);

	public double getDeltaShadow();

}
