// THIS FILE HAS BEEN GENERATED BY A PREPROCESSOR.
package net.sourceforge.plantuml.style.parser;

enum StyleTokenType {
	OPEN_BRACKET, //
	CLOSE_BRACKET, //
	STRING, //
	COMMA, //
	STAR, //
	NEWLINE, //
	SEMICOLON, //
	COLON, //
	AROBASE_MEDIA, //
}
