// THIS FILE HAS BEEN GENERATED BY A PREPROCESSOR.
package net.sourceforge.plantuml.style.parser;

public class StyleParsingException extends Exception {

	public StyleParsingException(String msg) {
		super(msg);
	}

}
