// THIS FILE HAS BEEN GENERATED BY A PREPROCESSOR.
package net.sourceforge.plantuml.svek.extremity;

import net.sourceforge.plantuml.klimt.shape.UDrawable;

public interface MiddleFactory {

	public UDrawable createUDrawable(double angle);

}
